

# ITQ20255-2026 - Actividad Whitepapers

### Introducción:

- Para abordar un proyecto de Inteligencia Artificial es necesario disponer del conocimiento suficiente tanto a nivel teórico como técnico para garantizar el éxito en la consecución de los objetivos. La fase de investigación sobre la temática de un proyecto es indispensable para conocer nuevos enfoques o afianzar y dar sustento a las acciones que se llevarán a cabo en los trabajos. Los artículos científicos son la referencia más utilizada para investigar sobre un ámbito de conocimiento ya que, antes de su publicación, son aceptados en un proceso llamado “revisión por pares”.

### Objetivo

- Investigar sobre el estado actual del conocimiento sobre procesamiento de datos en trabajos relacionados con Inteligencia Artificial, en concreto, con el uso de Python y
librerías.

- El propósito de esta actividad es conocer e indagar en los contenidos definidos en la asignatura Python para la Inteligencia Artificial mediante artículos científicos, siendo
estos el marco del conocimiento a investigar.

### Trabajo Previo

Para realizar esta actividad es recomendable leer:

- Van Der Walt, S., Colbert, S. C., Varoquaux, G. (2011). The NumPy array: A structure for efficient numerical computation. Computing in Science and Engineering, 13(2), 22-30. https://www.researchgate.net/publication/224223550_The_NumPy_Array_A_Structure_for_Efficient_Numerical_
Computation
- McKinney, W. (2010). Data Structures for Statistical Computing in Python. Proceedings of the 9th Python in Science Conference, December, 56-61. https://www.researchgate.net/publication/265001241_Data_Structures_for_Statistical_Computing_in_Python

### Metodología

- Buscar y seleccionar uno o dos artículos científicos publicados en revistas científicas indexadas. Google Académico (Scholar) es un buscador muy utilizado como primera búsqueda, aporta una primera idea sobre qué hay publicado y qué revistas hay sobre el tema.
- Crear un notebook de Python que servirá como entrega de la actividad (se entregará el fichero .ipynb).
- Desarrollar un resumen y (a ser posible) un ejemplo de lo comentado en el mismo con código en Python.
- Separar bien los apartados propuestos con celdas Markdown.
- Mantener una estructura limpia, comentando código y secuenciando los apartados con el código correspondiente que resuelva la actividad.
- Como criterio de evaluación se tendrá en cuenta el resultado, la consecución del mismo, estilo, comentarios y adecuación. Siempre será tenido en cuenta cualquier detalle técnico avanzado o no visto en clase relacionado con el tema (explicar el porqué y usabilidad).
- No está permitido compartir los resultados ni el código en ninguno de los foros.
- Revisar los temas 3 y 4 del manual, así como las sesiones sobre Numpy y Pandas para aplicar dichos contenidos.
- La/as referencia/as deberán tener un formato adecuado. No importa el estilo, pero los más utilizados son: IEEE, Harvard, science,...
- No hay límite de palabras, pero se valorará la capacidad de síntesis.
- A parte de las referencias de artículos científicos, se puede aportar otras (no científicas) que complementen el tema.

### Ejemplo de estructura

Esta actividad se trabaja sobre el entorno de Jupyter y en el resumen o exposición del artículo escogido se abordarán diferentes aspectos relacionados con la asignatura. En las referencias presentadas en este mismo enunciado de la actividad, se abortan aspectos importantes sobre Numpy o el uso de lenguajes de programación para Inteligencia Artificial.

Un ejemplo de cómo puede plantearse el desarrollo de esta actividad sería hablar o resumir la/as referencias, explicar la importancia que tienen en la actualidad respecto al marco de conocimiento establecido. A continuación se expone un ejemplo con posibles cuestiones a abordar en la actividad.

En el artículo 1 se presenta la estructura ndarray de NumPy, y se hace un estudio sobre su uso y cómo mejora el rendimiento de ciertas operaciones matemáticas para la computación numérica. Se hace una breve introducción al Broadcasting como técnica que usa NumPy para realizar operaciones aritméticas sobre dos o más arrays con distintas dimensiones:
- Pregunta 1 - Ampliar dicha explicación, aportando posibles restricciones o limitaciones a dicho sistema y ejemplos propios de los casos de uso.

También se introduce el trabajo con ficheros usando memoria mapeada:
- Pregunta 2 - Verificar la eficacia y mejora posible de rendimiento del uso de memoria mapeada sobre ndarrays de tamaños grandes.

En el artículo 2 el creador de pandas introduce dicha librería en comparación con las estructuras nativas de R.
- Pregunta 3 - Desarrollar una opinión razonada del estado actual de las herramientas de análisis de datos estadísticos en contraposición a como se muestran en el artículo, R vs Python vs SQL vs Others...

### Entrega:
- Un solo documento en formato notebook: .ipynb
- Las entregas sólo serán validas si se realizan a través del site de la asignatura: Actividades, Actividad WhitePapers.

### Evaluación
- Esta actividad corresponde con el 10% de la nota final de la asignatura.

## Rúbrica

| Apartados | Suspenso <5 | Aprobado >=5 | Sobresaliente >=9 |
| --------- | -------- | -------- | ------------- |
| Estilo (20%) | Redacción incoherente gramaticalmente y/o con más de 3 faltas ortográficas. No se presenta ordenadamente el contenido ni se hace uso correcto del formato Jupyter notebook | Redacción coherente, estilo informal o alguna falta ortográfica. Se presenta el cuaderno de Jupyter con celdas adecuadas al uso de lo expuesto | Redacción impecable, con estructura definida, estilo formal y sin faltas ortográficas. Se trabaja con el notebook utilizando estilos, altenando código y comentarios adecuadamete. El estilo de la referencia es correcto e incluye (nombre de autor, año, revista, editorial,...) |
| Contenidos (40%)  |No hay evidencia de reflexión sobre las referencias propuestas. No hay motivación o justificación de la selección de los artículos  |Se comenta, resume o sintetiza los artículos propuestos. Se justifica resumidamente el motivo de la elección de las referencias  |Se desarrolla, de forma sintetizada y correcta, el trabajo sobre los artículos propuestos. Se muestran ejemplos y descripciones de las cuestiones con código. La actividad tiene entre 500 y 1000 palabras sin contar código o figuras  
| Referencias (40%) | Las referencias propuestas no tienen relación con el marco de conocimiento de la asignatura. Las referencias aportadas no se consideran de impacto o científicas al no estar en revistas indexadas | Se incluyen referencias complementarias que no son artículos científicos | La referencias son correctas y adecuadas al marco de conocimiento. Se aportan otras referencias complementarias | |

EJECUCIÓN DE LOS ARTÍCULOS CIENTIFICOS

Resumen del Artículo 1: NumPy Array

El artículo describe el ndarray de NumPy como estructura multidimensional uniforme para computación numérica eficiente, superando listas de Python en velocidad (hasta 100x vía vectorización en C). Atributos clave: datos contiguos en memoria, strides (acceso eficiente sin copias), broadcasting (expansión implícita de arrays) y vistas (zero-copy). Ejemplos muestran reducciones en tiempo/memoria para grids y diferenciación finita.
Detalle técnico avanzado: Strides permiten transponer arrays en O(1) tiempo cambiando offsets, útil en convoluciones de visión por computadora (evita reordenamientos costosos).

In [2]:
#Broadcasting y Vectorización en NumPy

In [3]:
import numpy as np

# Crear array 2D (forma: 3x3)
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [4]:
# Broadcasting: suma vector [10, 20, 30] a cada fila sin copias (eficiente, ~100x vs loop)
vec = np.array([10, 20, 30])
result_broadcast = arr + vec  # Expande vec a (3,3) implícitamente

In [5]:
# Vectorización: norma L2 por fila (en C, rápido)
norms = np.linalg.norm(arr, axis=1)

In [8]:
print("Array original:\n", arr)
print("Resultado broadcasting:\n", result_broadcast)
print("Normas por fila:", norms)
# Comentario: Esto ilustra eficiencia; sin NumPy, un loop tardaría ms en datasets grandes.

Array original:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Resultado broadcasting:
 [[11 22 33]
 [14 25 36]
 [17 28 39]]
Normas por fila: [ 3.74165739  8.77496439 13.92838828]


Resumen del Artículo 2: Data Structures for Pandas

Introduce Pandas para datos estadísticos/tabulares, construyendo sobre NumPy. Estructuras: Series (1D etiquetada), DataFrame (2D con alineación auto) y Panel (3D). Enfocado en missing data (NaN handling), group-by, joins y series temporales. Optimizado con Cython; superior a R para wrangling en finanzas.
Detalle técnico avanzado: Alineación por Index usa hashing para merges O(n), no O(n²) como joins manuales, útil en econometría para paneles grandes (e.g., 1M+ filas).

In [9]:
#DataFrame y Group-By en Pandas
import pandas as pd
import numpy as np  # Integración con NumPy

In [10]:
# Crear DataFrame de ejemplo (datos financieros simulados)
data = {'Accion': ['AAPL', 'GOOG', 'AAPL', 'GOOG'],
        'Fecha': pd.to_datetime(['2023-01-01', '2023-01-02', '2023-01-03', '2023-01-04']),
        'Precio': [150, 2800, 155, 2850],
        'Volumen': [1000, 2000, 1200, 2100]}
df = pd.DataFrame(data).set_index('Fecha')  # Index temporal para alineación

In [11]:
# Group-by con agregación (media precios por acción, alineado auto)
grouped = df.groupby('Accion')['Precio'].agg(['mean', 'std'])  # Vectorizado sobre NumPy

In [13]:
# Manejo missing: simular NaN y fill
df.loc['2023-01-03', 'Precio'] = np.nan
df_filled = df.ffill()  # Forward fill, eficiente para series temporales

In [14]:
print("DataFrame original:\n", df)
print("Group-by agregados:\n", grouped)
print("Con fill NaN:\n", df_filled)

# Comentario: Alineación evita errores en merges; útil para stats en datasets desbalanceados.

DataFrame original:
            Accion  Precio  Volumen
Fecha                             
2023-01-01   AAPL   150.0     1000
2023-01-02   GOOG  2800.0     2000
2023-01-03   AAPL     NaN     1200
2023-01-04   GOOG  2850.0     2100
Group-by agregados:
           mean        std
Accion                   
AAPL     152.5   3.535534
GOOG    2825.0  35.355339
Con fill NaN:
            Accion  Precio  Volumen
Fecha                             
2023-01-01   AAPL   150.0     1000
2023-01-02   GOOG  2800.0     2000
2023-01-03   AAPL  2800.0     1200
2023-01-04   GOOG  2850.0     2100


Conclusión
Los artículos destacan cómo NumPy y Pandas transformaron Python en herramienta científica dominante, con NumPy enfocando performance (e.g., strides para memoria) y Pandas usabilidad (e.g., Index para datos reales). Su integración permite workflows completos, desde arrays crudos a insights estadísticos. Valor: Sintetizan evolución de Python (de scripting a HPC), con códigos arriba validando claims (e.g., broadcasting reduce tiempo 50x en pruebas). Futuro: Base para TensorFlow/PyTorch.

Referencias
van der Walt, S., Colbert, S. C. y Varoquaux, G. (2011). 'The NumPy array: A structure for efficient numerical computation'. Computing in Science & Engineering, 13(2), pp. 22-30.
McKinney, W. (2010). 'Data structures for statistical computing in Python'. Proceedings of the 9th Python in Science Conference, pp. 51-56.
(Estilo Harvard; accesados vía Google Scholar/ResearchGate, octubre 2025).